stages:
- stage: Build
  jobs:
  - job: build
    pool: { vmImage: ubuntu-latest }
    steps:
    - script: npm ci && npm test
    - task: PublishPipelineArtifact@1
      inputs: { targetPath: ".", artifact: drop }

- stage: Deploy
  dependsOn: Build
  jobs:
  - deployment: deployWeb
    environment: producao
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - script: echo "Implantando TaskFlow..."